/**
 * 
 */
package co.edu.usco.lcms.utility;

/**
 * @author jankarlos
 *
 */

public class Constantes {

	public String WEP_MODALIDAD;
	public String WEP_NIVEL_ACADEMICO;
	public String WEP_NUCLEO;
	public String WEP_FORMALIDAD;
	public String WEP_FACULTAD_TIPO;
	public String WEP_TIPO_UAA;
	public String WEP_SALAS;
	public String WEP_NUMERO_LICENCIAS;
	public String WEP_HORAS;
	public String WEP_HORARIO;
	public String WEP_TIPO_OCUPACION;
	public String WEP_ROLE_ADMINISTRADOR_LCMS;
	public String WEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS;
	public String WEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS;
	public String WEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS;
	public String WEP_ROLE_DOCENTE;
	public String WEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS;
	public String WEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS;
	public String WEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA;
	public String RUTA;
	public String RUTA_CAS;
	public String RUTA_PORTAL;
	public String ADOBE_CONNECT_FOLDER_ID;
	public String WEP_ESTADO_ELIMINADO_CURSO;
	public String WEP_ESTADO_ELIMINADO_OFERTA;
	public String WEP_TIPO_ESPACIO_VIRTUAL;
	public String WEP_CODIGO_HORA_FIN;

	public Constantes() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param wEP_MODALIDAD
	 * @param wEP_NIVEL_ACADEMICO
	 * @param wEP_NUCLEO
	 * @param wEP_FORMALIDAD
	 * @param wEP_FACULTAD_TIPO
	 * @param wEP_TIPO_UAA
	 * @param wEP_SALAS
	 * @param wEP_NUMERO_LICENCIAS
	 * @param wEP_HORAS
	 * @param wEP_HORARIO
	 * @param wEP_TIPO_OCUPACION
	 * @param wEP_ROLE_ADMINISTRADOR_LCMS
	 * @param wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS
	 * @param wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS
	 * @param wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS
	 * @param wEP_ROLE_DOCENTE
	 * @param wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS
	 * @param wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS
	 * @param wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA
	 * @param rUTA
	 * @param rUTA_CAS
	 * @param rUTA_PORTAL
	 * @param aDOBE_CONNECT_FOLDER_ID
	 * @param wEP_ESTADO_ELIMINADO_CURSO
	 * @param wEP_ESTADO_ELIMINADO_OFERTA
	 * @param wEP_TIPO_ESPACIO_VIRTUAL
	 * @param wEP_CODIGO_HORA_FIN
	 */
	public Constantes(String wEP_MODALIDAD, String wEP_NIVEL_ACADEMICO, String wEP_NUCLEO, String wEP_FORMALIDAD,
			String wEP_FACULTAD_TIPO, String wEP_TIPO_UAA, String wEP_SALAS, String wEP_NUMERO_LICENCIAS,
			String wEP_HORAS, String wEP_HORARIO, String wEP_TIPO_OCUPACION, String wEP_ROLE_ADMINISTRADOR_LCMS,
			String wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS, String wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS,
			String wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS, String wEP_ROLE_DOCENTE,
			String wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS, String wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS,
			String wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA, String rUTA, String rUTA_CAS, String rUTA_PORTAL,
			String aDOBE_CONNECT_FOLDER_ID, String wEP_ESTADO_ELIMINADO_CURSO, String wEP_ESTADO_ELIMINADO_OFERTA,
			String wEP_TIPO_ESPACIO_VIRTUAL, String wEP_CODIGO_HORA_FIN) {
		super();
		WEP_MODALIDAD = wEP_MODALIDAD;
		WEP_NIVEL_ACADEMICO = wEP_NIVEL_ACADEMICO;
		WEP_NUCLEO = wEP_NUCLEO;
		WEP_FORMALIDAD = wEP_FORMALIDAD;
		WEP_FACULTAD_TIPO = wEP_FACULTAD_TIPO;
		WEP_TIPO_UAA = wEP_TIPO_UAA;
		WEP_SALAS = wEP_SALAS;
		WEP_NUMERO_LICENCIAS = wEP_NUMERO_LICENCIAS;
		WEP_HORAS = wEP_HORAS;
		WEP_HORARIO = wEP_HORARIO;
		WEP_TIPO_OCUPACION = wEP_TIPO_OCUPACION;
		WEP_ROLE_ADMINISTRADOR_LCMS = wEP_ROLE_ADMINISTRADOR_LCMS;
		WEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS = wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS;
		WEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS = wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS;
		WEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS = wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS;
		WEP_ROLE_DOCENTE = wEP_ROLE_DOCENTE;
		WEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS = wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS;
		WEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS = wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS;
		WEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA = wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA;
		RUTA = rUTA;
		RUTA_CAS = rUTA_CAS;
		RUTA_PORTAL = rUTA_PORTAL;
		ADOBE_CONNECT_FOLDER_ID = aDOBE_CONNECT_FOLDER_ID;
		WEP_ESTADO_ELIMINADO_CURSO = wEP_ESTADO_ELIMINADO_CURSO;
		WEP_ESTADO_ELIMINADO_OFERTA = wEP_ESTADO_ELIMINADO_OFERTA;
		WEP_TIPO_ESPACIO_VIRTUAL = wEP_TIPO_ESPACIO_VIRTUAL;
		WEP_CODIGO_HORA_FIN = wEP_CODIGO_HORA_FIN;
	}

	/**
	 * @return the wEP_MODALIDAD
	 */
	public String getWEP_MODALIDAD() {
		return WEP_MODALIDAD;
	}

	/**
	 * @param wEP_MODALIDAD the wEP_MODALIDAD to set
	 */
	public void setWEP_MODALIDAD(String wEP_MODALIDAD) {
		WEP_MODALIDAD = wEP_MODALIDAD;
	}

	/**
	 * @return the wEP_NIVEL_ACADEMICO
	 */
	public String getWEP_NIVEL_ACADEMICO() {
		return WEP_NIVEL_ACADEMICO;
	}

	/**
	 * @param wEP_NIVEL_ACADEMICO the wEP_NIVEL_ACADEMICO to set
	 */
	public void setWEP_NIVEL_ACADEMICO(String wEP_NIVEL_ACADEMICO) {
		WEP_NIVEL_ACADEMICO = wEP_NIVEL_ACADEMICO;
	}

	/**
	 * @return the wEP_NUCLEO
	 */
	public String getWEP_NUCLEO() {
		return WEP_NUCLEO;
	}

	/**
	 * @param wEP_NUCLEO the wEP_NUCLEO to set
	 */
	public void setWEP_NUCLEO(String wEP_NUCLEO) {
		WEP_NUCLEO = wEP_NUCLEO;
	}

	/**
	 * @return the wEP_FORMALIDAD
	 */
	public String getWEP_FORMALIDAD() {
		return WEP_FORMALIDAD;
	}

	/**
	 * @param wEP_FORMALIDAD the wEP_FORMALIDAD to set
	 */
	public void setWEP_FORMALIDAD(String wEP_FORMALIDAD) {
		WEP_FORMALIDAD = wEP_FORMALIDAD;
	}

	/**
	 * @return the wEP_FACULTAD_TIPO
	 */
	public String getWEP_FACULTAD_TIPO() {
		return WEP_FACULTAD_TIPO;
	}

	/**
	 * @param wEP_FACULTAD_TIPO the wEP_FACULTAD_TIPO to set
	 */
	public void setWEP_FACULTAD_TIPO(String wEP_FACULTAD_TIPO) {
		WEP_FACULTAD_TIPO = wEP_FACULTAD_TIPO;
	}

	/**
	 * @return the wEP_TIPO_UAA
	 */
	public String getWEP_TIPO_UAA() {
		return WEP_TIPO_UAA;
	}

	/**
	 * @param wEP_TIPO_UAA the wEP_TIPO_UAA to set
	 */
	public void setWEP_TIPO_UAA(String wEP_TIPO_UAA) {
		WEP_TIPO_UAA = wEP_TIPO_UAA;
	}

	/**
	 * @return the wEP_SALAS
	 */
	public String getWEP_SALAS() {
		return WEP_SALAS;
	}

	/**
	 * @param wEP_SALAS the wEP_SALAS to set
	 */
	public void setWEP_SALAS(String wEP_SALAS) {
		WEP_SALAS = wEP_SALAS;
	}

	/**
	 * @return the wEP_NUMERO_LICENCIAS
	 */
	public String getWEP_NUMERO_LICENCIAS() {
		return WEP_NUMERO_LICENCIAS;
	}

	/**
	 * @param wEP_NUMERO_LICENCIAS the wEP_NUMERO_LICENCIAS to set
	 */
	public void setWEP_NUMERO_LICENCIAS(String wEP_NUMERO_LICENCIAS) {
		WEP_NUMERO_LICENCIAS = wEP_NUMERO_LICENCIAS;
	}

	/**
	 * @return the wEP_HORAS
	 */
	public String getWEP_HORAS() {
		return WEP_HORAS;
	}

	/**
	 * @param wEP_HORAS the wEP_HORAS to set
	 */
	public void setWEP_HORAS(String wEP_HORAS) {
		WEP_HORAS = wEP_HORAS;
	}

	/**
	 * @return the wEP_HORARIO
	 */
	public String getWEP_HORARIO() {
		return WEP_HORARIO;
	}

	/**
	 * @param wEP_HORARIO the wEP_HORARIO to set
	 */
	public void setWEP_HORARIO(String wEP_HORARIO) {
		WEP_HORARIO = wEP_HORARIO;
	}

	/**
	 * @return the wEP_TIPO_OCUPACION
	 */
	public String getWEP_TIPO_OCUPACION() {
		return WEP_TIPO_OCUPACION;
	}

	/**
	 * @param wEP_TIPO_OCUPACION the wEP_TIPO_OCUPACION to set
	 */
	public void setWEP_TIPO_OCUPACION(String wEP_TIPO_OCUPACION) {
		WEP_TIPO_OCUPACION = wEP_TIPO_OCUPACION;
	}

	/**
	 * @return the wEP_ROLE_ADMINISTRADOR_LCMS
	 */
	public String getWEP_ROLE_ADMINISTRADOR_LCMS() {
		return WEP_ROLE_ADMINISTRADOR_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMINISTRADOR_LCMS the wEP_ROLE_ADMINISTRADOR_LCMS to set
	 */
	public void setWEP_ROLE_ADMINISTRADOR_LCMS(String wEP_ROLE_ADMINISTRADOR_LCMS) {
		WEP_ROLE_ADMINISTRADOR_LCMS = wEP_ROLE_ADMINISTRADOR_LCMS;
	}

	/**
	 * @return the wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS
	 */
	public String getWEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS() {
		return WEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS the wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS to set
	 */
	public void setWEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS(String wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS) {
		WEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS = wEP_ROLE_ADMINISTRADOR_FACULTAD_LCMS;
	}

	/**
	 * @return the wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS
	 */
	public String getWEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS() {
		return WEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS the wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS to set
	 */
	public void setWEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS(String wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS) {
		WEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS = wEP_ROLE_ADMIN_VIDEOCONFERENCIA_LCMS;
	}

	/**
	 * @return the wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS
	 */
	public String getWEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS() {
		return WEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS the wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS to set
	 */
	public void setWEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS(String wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS) {
		WEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS = wEP_ROLE_ADMIN_VIDEOCONFERENCIA_FACULTAD_LCMS;
	}

	/**
	 * @return the wEP_ROLE_DOCENTE
	 */
	public String getWEP_ROLE_DOCENTE() {
		return WEP_ROLE_DOCENTE;
	}

	/**
	 * @param wEP_ROLE_DOCENTE the wEP_ROLE_DOCENTE to set
	 */
	public void setWEP_ROLE_DOCENTE(String wEP_ROLE_DOCENTE) {
		WEP_ROLE_DOCENTE = wEP_ROLE_DOCENTE;
	}

	/**
	 * @return the wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS
	 */
	public String getWEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS() {
		return WEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS the wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS to set
	 */
	public void setWEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS(String wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS) {
		WEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS = wEP_ROLE_ADMIN_PROG_ACADEMICA_LCMS;
	}

	/**
	 * @return the wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS
	 */
	public String getWEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS() {
		return WEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS;
	}

	/**
	 * @param wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS the wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS to set
	 */
	public void setWEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS(String wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS) {
		WEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS = wEP_ROLE_ADMIN_FACULTAD_PROG_ACADEMICA_LCMS;
	}

	/**
	 * @return the wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA
	 */
	public String getWEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA() {
		return WEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA;
	}

	/**
	 * @param wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA the wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA to set
	 */
	public void setWEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA(String wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA) {
		WEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA = wEP_EDUCACION_VIRTUAL_PERFILES_SISTEMA;
	}

	/**
	 * @return the rUTA
	 */
	public String getRUTA() {
		return RUTA;
	}

	/**
	 * @param rUTA the rUTA to set
	 */
	public void setRUTA(String rUTA) {
		RUTA = rUTA;
	}

	/**
	 * @return the rUTA_CAS
	 */
	public String getRUTA_CAS() {
		return RUTA_CAS;
	}

	/**
	 * @param rUTA_CAS the rUTA_CAS to set
	 */
	public void setRUTA_CAS(String rUTA_CAS) {
		RUTA_CAS = rUTA_CAS;
	}

	/**
	 * @return the rUTA_PORTAL
	 */
	public String getRUTA_PORTAL() {
		return RUTA_PORTAL;
	}

	/**
	 * @param rUTA_PORTAL the rUTA_PORTAL to set
	 */
	public void setRUTA_PORTAL(String rUTA_PORTAL) {
		RUTA_PORTAL = rUTA_PORTAL;
	}

	/**
	 * @return the aDOBE_CONNECT_FOLDER_ID
	 */
	public String getADOBE_CONNECT_FOLDER_ID() {
		return ADOBE_CONNECT_FOLDER_ID;
	}

	/**
	 * @param aDOBE_CONNECT_FOLDER_ID the aDOBE_CONNECT_FOLDER_ID to set
	 */
	public void setADOBE_CONNECT_FOLDER_ID(String aDOBE_CONNECT_FOLDER_ID) {
		ADOBE_CONNECT_FOLDER_ID = aDOBE_CONNECT_FOLDER_ID;
	}

	/**
	 * @return the wEP_ESTADO_ELIMINADO_CURSO
	 */
	public String getWEP_ESTADO_ELIMINADO_CURSO() {
		return WEP_ESTADO_ELIMINADO_CURSO;
	}

	/**
	 * @param wEP_ESTADO_ELIMINADO_CURSO the wEP_ESTADO_ELIMINADO_CURSO to set
	 */
	public void setWEP_ESTADO_ELIMINADO_CURSO(String wEP_ESTADO_ELIMINADO_CURSO) {
		WEP_ESTADO_ELIMINADO_CURSO = wEP_ESTADO_ELIMINADO_CURSO;
	}

	/**
	 * @return the wEP_ESTADO_ELIMINADO_OFERTA
	 */
	public String getWEP_ESTADO_ELIMINADO_OFERTA() {
		return WEP_ESTADO_ELIMINADO_OFERTA;
	}

	/**
	 * @param wEP_ESTADO_ELIMINADO_OFERTA the wEP_ESTADO_ELIMINADO_OFERTA to set
	 */
	public void setWEP_ESTADO_ELIMINADO_OFERTA(String wEP_ESTADO_ELIMINADO_OFERTA) {
		WEP_ESTADO_ELIMINADO_OFERTA = wEP_ESTADO_ELIMINADO_OFERTA;
	}

	/**
	 * @return the wEP_TIPO_ESPACIO_VIRTUAL
	 */
	public String getWEP_TIPO_ESPACIO_VIRTUAL() {
		return WEP_TIPO_ESPACIO_VIRTUAL;
	}

	/**
	 * @param wEP_TIPO_ESPACIO_VIRTUAL the wEP_TIPO_ESPACIO_VIRTUAL to set
	 */
	public void setWEP_TIPO_ESPACIO_VIRTUAL(String wEP_TIPO_ESPACIO_VIRTUAL) {
		WEP_TIPO_ESPACIO_VIRTUAL = wEP_TIPO_ESPACIO_VIRTUAL;
	}

	/**
	 * @return the wEP_CODIGO_HORA_FIN
	 */
	public String getWEP_CODIGO_HORA_FIN() {
		return WEP_CODIGO_HORA_FIN;
	}

	/**
	 * @param wEP_CODIGO_HORA_FIN the wEP_CODIGO_HORA_FIN to set
	 */
	public void setWEP_CODIGO_HORA_FIN(String wEP_CODIGO_HORA_FIN) {
		WEP_CODIGO_HORA_FIN = wEP_CODIGO_HORA_FIN;
	}

	
}